applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todo_empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar_por_area/<shortname>/', views.ListByAreaEmpleados.as_view(), name='empleados_area'),
    path('lista_empleados_admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),    
    path('buscar_empleado/', views.ListEmpleadosByKeyword.as_view()),
    path('lista_habilidades_empleado/', views.ListHabilidadesEmpleados.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),    
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento,
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la app departamento,
    re_path('', include('applications.persona.urls')),
    # incluimos las urls de la app home,
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    def __str__(self):
        return '{}, {}'.format(self.id, self.habilidad)

class Empleado(models.Model):

    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTROS'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    department = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)

    def __str__(self):
        return '{}, {}, {}, {}, {}'.format(self.id, self.first_name, self.last_name, self.job, self.department)

applications/persona/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado

        fields = (
            'first_name',
            'last_name',
            'job',
            'department',
            'habilidades',
            'avatar',
        )

        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Empleado
from .forms import EmpleadoForm


# Create your views here.

class InicioView(TemplateView):
    template_name = 'inicio.html'


class ListAllEmpleados(ListView):
    """
        Lista todos los empleados en total
    """

    template_name = 'persona/list_all.html'
    paginate_by = 4
    context_object_name = 'empleados'

    def get_queryset(self):
        keyword = self.request.GET.get('keyword', '')
        lista = Empleado.objects.filter(
            full_name__icontains = keyword
        )

        return lista


class ListaEmpleadosAdmin(ListView):
    """
        Lista todos los empleados en total
    """

    template_name = 'persona/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado


class ListByAreaEmpleados(ListView):
    """
        Lista los empleados de un área específica
    """

    template_name = 'persona/list_by_area.html'

    def get_queryset(self):
        area = self.kwargs['shortname']
        return Empleado.objects.filter(
            department__short_name = area
        )


class ListEmpleadosByKeyword(ListView):
    """
        Lista los empleados por palabra clave
    """

    template_name = 'persona/list_by_keyword.html'
    context_object_name = 'Empleados'

    def get_queryset(self):
        keyword = self.request.GET.get('keyword', '')
        lista = Empleado.objects.filter(
            first_name = keyword
        )
        return lista


class ListHabilidadesEmpleados(ListView):
    """
        Lista los empleados por habilidades
    """

    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id = 1)
        return empleado.habilidades.all()


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detail_empleado.html'

    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'

        return context


class SuccessView(TemplateView):
    template_name = 'persona/success.html'


class EmpleadoCreateView(CreateView):
    template_name = 'persona/add.html'
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_admin')

    def form_valid(self, form):
        # lógica de la función
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = 'persona/update.html'
    fields = [
        'first_name',
        'last_name',
        'job',
        'department',
        'habilidades'
    ]

    success_url = reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # lógica de la función
        return super(EmpleadoUpdateView, self).form_valid(form)    


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'persona/delete.html'

    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
Registrar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Empleado</h1>

        <form method="post" class="cell grid-x grid-margin-x" enctype="multipart/form-data"> {% csrf_token %}

            <div class="cell large-6 medium-6">
                <label>Nombres:
                    {{ form.first_name }}
                </label>
            </div>
            <div class="cell large-6 medium-6">
                <label>Apellidos:
                    {{ form.last_name }}
                </label>
            </div>
            <div class="cell large-6 medium-6">
                <label>Trabajo
                    {{ form.job }}
                </label>
            </div>
            <div class="cell large-6 medium-6">
                <label>Área:
                    {{ form.department }}
                </label>
            </div>
            <div class="cell large-12 medium-12">
                <label>Habilidades extra:
                    {{ form.habilidades }}
                </label>
            </div>
            <div class="cell large-12 medium-12">
                <label>Foto:
                    {{ form.avatar }}
                </label>
            </div>            
            <div class="cell">
                <button type="submit" class="success button">Guardar</button>
            </div>

        </form>
    </div>


</div>

{% endblock content %}

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
Eliminar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{object.full_name}}</h1>
        <form class="cell" method="post"> {% csrf_token %}

            <div class="callout secondary">
                <h5>¿Desea elminar este empleado?</h5>
                <button type="submit" class="alert button">Eliminar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{object.full_name}}
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
                <div class="card-divider">
                    {{ empleado.get_job_display }}
                </div>
                
                {% if empleado.avatar %}
                    <img src="{{ empleado.avatar.url }}">
                {% else %}
                    <img src="{% static 'img/20.jpg' %}">
                {% endif %}

                <div class="card-section">
                    <h4>{{ empleado.full_name }}</h4>
                    <p>{{ empleado.department.short_name }}</p>
                    <p><span class="label">Habilidades</span></p>

                    <ul class="vertical menu">
                        
                        {% for h in empleado.habilidades.all %}
                            <li>
                                {{ h.habilidad }}
                            </li>
                        {% endfor %}
                        
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/persona/habilidades.html
<h1>Habilidades</h1>

<ul>
    {% for h in habilidades %}
    <li>
        {{ h }}
    </li>

    {% endfor %}

</ul>

templates/persona/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>

        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="keyword" id="keyword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>

        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Acción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.department }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated%}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                            <span class="show-for-sr">page</span>
                        </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}
                        {% ifequal pagina page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">You're on page</span>
                                {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pagina }}" >{{ pagina }}</a>
                            </li>
                        {% endifequal %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">
                                Siguiente
                            </a>
                        </li>                        
                    {% endif %}

                </ul>
            </nav>
            {% endif %}
        </div>
    </div>

</div>

{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>

        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="keyword" id="keyword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>

        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Acción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.department }}</td>
                        <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated%}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                            <span class="show-for-sr">page</span>
                        </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}
                        {% ifequal pagina page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">You're on page</span>
                                {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pagina }}" >{{ pagina }}</a>
                            </li>
                        {% endifequal %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">
                                Siguiente
                            </a>
                        </li>                        
                    {% endif %}

                </ul>
            </nav>
            {% endif %}
        </div>
    </div>

</div>

{% endblock content %}

templates/persona/list_by_keyword.html
<h1>Keywords</h1>


<form method="get"> {% csrf_token %}
    <input type="text" name="keyword" id="keyword" placeholder="ingrese nombre">

    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>

<ul>
    {% for i in personas %}

    <li>
        {{ i }}
    </li>
    {% endfor %}
</ul>

templates/persona/lista_empleados.html
{% extends 'base.html' %}

{% block title %}
Administrar Empleados
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">

    <div class="grid-x">
        <h1 class="cell">Administrar Empleados</h1>

        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" name="keyword" id="keyword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>

        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Acción</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.first_name }}</td>
                        <td>{{ e.last_name }}</td>
                        <td>{{ e.department }}</td>
                        <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">
                                Editar
                            </a>
                        </td>
                        <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">
                                Eliminar
                            </a>
                        </td>                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated%}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                            <span class="show-for-sr">page</span>
                        </li>
                    {% endif %}


                    {% for pagina in paginator.page_range %}
                        {% ifequal pagina page_obj.number %}
                            <li class="current">
                                <span class="show-for-sr">You're on page</span>
                                {{ pagina }}
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ pagina }}" >{{ pagina }}</a>
                            </li>
                        {% endifequal %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">
                                Siguiente
                            </a>
                        </li>                        
                    {% endif %}

                </ul>
            </nav>
            {% endif %}
        </div>
    </div>

</div>

{% endblock content %}

templates/persona/success.html
<h1>Success</h1>

templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
Modificar Empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Modificar</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="post"> {% csrf_token %}

                    <div class="cell large-6 medium-6">
                        <label>Nombres:
                            {{ form.first_name }}
                        </label>
                    </div>
                    <div class="cell large-6 medium-6">
                        <label>Apellidos:
                            {{ form.last_name }}
                        </label>
                    </div>
                    <div class="cell large-6 medium-6">
                        <label>Trabajo
                            {{ form.job }}
                        </label>
                    </div>
                    <div class="cell large-6 medium-6">
                        <label>Área:
                            {{ form.department }}
                        </label>
                    </div>
                    <div class="cell large-6 medium-6">
                        <label>Habilidades extra:
                            {{ form.habilidades }}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Modificar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}