applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamento_lista/', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new_departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todo_empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar_por_area/<shortname>/', views.ListByAreaEmpleados.as_view(), name='empleados_area'),
    path('lista_empleados_admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),    
    path('buscar_empleado/', views.ListEmpleadosByKeyword.as_view()),
    path('lista_habilidades_empleado/', views.ListHabilidadesEmpleados.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),    
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento,
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la app departamento,
    re_path('', include('applications.persona.urls')),
    # incluimos las urls de la app home,
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li> <a href="/" style="color: black;">Empleados</a></li>
            <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>
            <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
            <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>            
            <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
        </ul>
    </div>
</div>