applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamento_lista/', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new_departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todo_empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar_por_area/<shortname>/', views.ListByAreaEmpleados.as_view(), name='empleados_area'),
    path('lista_empleados_admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),    
    path('buscar_empleado/', views.ListEmpleadosByKeyword.as_view()),
    path('lista_habilidades_empleado/', views.ListHabilidadesEmpleados.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='empleado_detail'),
    path('add_empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('delete_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),    
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # incluimos las urls de la app departamento,
    re_path('', include('applications.departamento.urls')),
    # incluimos las urls de la app departamento,
    re_path('', include('applications.persona.urls')),
    # incluimos las urls de la app home,
    re_path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20)
    anulate = models.BooleanField('Anulado', default=False)

    def __str__(self):
        return '{}, {}, {}'.format(self.id, self.name, self.short_name)

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):

    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short_name = forms.CharField(max_length=20)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView

from .forms import NewDepartamentoForm
from applications.persona.models import Empleado
from .models import Departamento

# Create your views here.

class DepartamentoListView(ListView):
    template_name = 'departamento/lista.html'
    model = Departamento
    context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'

    form_class = NewDepartamentoForm

    success_url = '.'

    def form_valid(self, form):

        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        departamento = form.cleaned_data['departamento']
        short_name = form.cleaned_data['short_name']

        departamento_object = Departamento(
            name=departamento,
            short_name=short_name
        )
        departamento_object.save()

        Empleado.objects.create(
            first_name=nombre,
            last_name=apellidos,
            job='1',
            department=departamento_object
        )

        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista Departamentos
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Departamentos</h1>
        <div class="cell">
            <table>
                <tbody>
                    {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.short_name}}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.short_name %}">
                                    Ver Empleados
                                </a>
                            </td>
                        </tr>
                    {% endfor%}
                </tbody>
            </table>

        </div>
    </div>
</div>

{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
Registrar Departamento
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Añadir Empleado</h1>

        <form method="post" class="cell grid-x grid-margin-x" enctype="multipart/form-data"> {% csrf_token %}

            <h3 class="cell">Empleado a Cargo</h3>
            <div class="cell large-12 medium-12">
                <label>Nombres:
                    {{ form.nombre }}
                </label>
            </div>
            <div class="cell large-12 medium-12">
                <label>Apellidos:
                    {{ form.apellidos }}
                </label>
            </div>

            <h3 class="cell">Datos departamento</h3>
            <div class="cell large-12 medium-12">
                <label>Departamento:
                    {{ form.departamento }}
                </label>
            </div>
            <div class="cell large-12 medium-12">
                <label>Shortname:
                    {{ form.short_name }}
                </label>
            </div>        
            <div class="cell">
                <button type="submit" class="success button">Guardar</button>
            </div>

        </form>
    </div>


</div>

{% endblock content %}